### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by perfect01** [Xewdy444/CF-Clearance-Scraper#14]
(No Cloudflare challenge detected.) hello Xewdy444, any method to resolve?

**Comment by Xewdy444** [comment]
Can you provide some more information about this issue.

**Comment by perfect01** [comment]
> Can you provide some more information about this issue.

[21:13:54] [INFO] Launching headless browser...
[21:14:08] [INFO] Going to https://-----.com...
[21:14:14] [ERROR] No Cloudflare challenge detected.

it's showing it to me now, before it just couldn't solve it... and it gave timeout

**Comment by Xewdy444** [comment]
Try using a different user agent.

**Comment by perfect01** [comment]
> Try using a different user agent.

I tested several, none worked, the same message appears
could it be the website?

**Comment by Xewdy444** [comment]
If the website issued a challenge before the latest update to the scraper, then the website was most likely issuing the challenge due to certain HTTP headers that the Webkit browser was using (or lack of). It may also have been due to the user agent used, which by default was `Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko)`. I changed the scraper to use Firefox because Cloudflare has a hard time verifying newer versions of Webkit for some reason, and I wanted users to be able to use the scraper with the latest version of Playwright. You can try changing the scraper to use Webkit again by simply editing a single line:

Line 70:
```py
browser = self._playwright.webkit.launch(headless=headless, proxy=proxy)
```

Then, just make sure you are using a Playwright version greater than or equal to 1.27.0 and less than or equal to 1.28.0.

**Comment by perfect01** [comment]
I'm going to test it soon, I need to sleep... I'll come back to let you know if it worked, thanks for the support

**Comment by silviucpp** [comment]
From my experience cloudflare the version of HTTP meters as well. While most probably your HTTP client it's using 1.1 the chrrome/ff browser it's using HTTP 2. 

To disable http2 in chrome use '--disable-http2' option

**Comment by Xewdy444** [comment]
> From my experience cloudflare the version of HTTP meters as well. While most probably your HTTP client it's using 1.1 the chrrome/ff browser it's using HTTP 2.
> 
> To disable http2 in chrome use '--disable-http2' option

This is also true. I have pushed an update that added the `--disable-http2` and `--disable-http3` options, which allow users to disable support for HTTP/2 and HTTP/3 for the Playwright browser.

**Comment by perfect01** [comment]
> > From my experience cloudflare the version of HTTP meters as well. While most probably your HTTP client it's using 1.1 the chrrome/ff browser it's using HTTP 2.
> > To disable http2 in chrome use '--disable-http2' option
> 
> This is also true. I have pushed an update that added the `--disable-http2` and `--disable-http3` options, which allow users to disable support for HTTP/2 and HTTP/3 for the Playwright browser.


unfortunately the problem persists, but congratulations on the update.
I don't know if it's allowed, but this is the website I'm trying to access
http://stake.best 
check if the problem occurs for you

**Comment by Xewdy444** [comment]
I was able to get this website to issue a managed challenge using this user agent: `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`. However, it had a difficult time verifying the browser, and I was only able to scrape a Cloudflare clearance cookie one time.

**Comment by Xewdy444** [comment]
```
python main.py -v -u https://stake.best/ -ua "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

**Comment by perfect01** [comment]
> If the website issued a challenge before the latest update to the scraper, then the website was most likely issuing the challenge due to certain HTTP headers that the Webkit browser was using (or lack of). It may also have been due to the user agent used, which by default was `Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko)`. I changed the scraper to use Firefox because Cloudflare has a hard time verifying newer versions of Webkit for some reason, and I wanted users to be able to use the scraper with the latest version of Playwright. You can try changing the scraper to use Webkit again by simply editing a single line:
> 
> Line 70:
> 
> ```python
> browser = self._playwright.webkit.launch(headless=headless, proxy=proxy)
> ```
> 
> Then, just make sure you are using a Playwright version greater than or equal to 1.27.0 and less than or equal to 1.28.0.

I didn't find out the real reason, but using "browser = self._playwright.webkit.launch(headless=headless, proxy=proxy)" with Firefox's UserAgent worked

thanks for the help guys
